name: "PR-title Checker"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vaishuvk/jira-issue-key-checker@v1
        with:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          jira-prefix: "ABC"
#           pass_on_octokit_error: false
