name: "PR-title Checker"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vaishuvk/PR-title-check@v1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          pass_on_octokit_error: false
