name: "PR-title Checker"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: fgiuliani/jira-issue-key-checker@v1.0.0
        with:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          pass_on_octokit_error: false
